# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 628)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 881, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 20, 261, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(220, 370, 219, 419))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 231, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self._2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self._2.setContentsMargins(11, 11, 11, 11)
        self._2.setSpacing(6)
        self._2.setObjectName("_2")
        self.comboBox_displacement_move_displacement_number = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_number.setObjectName("comboBox_displacement_move_displacement_number")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self.comboBox_displacement_move_displacement_number.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_number, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self._2.addWidget(self.label_8, 3, 1, 1, 1)
        self.comboBox_displacement_move_displacement_movement_mode = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_movement_mode.setEnabled(False)
        self.comboBox_displacement_move_displacement_movement_mode.setObjectName("comboBox_displacement_move_displacement_movement_mode")
        self.comboBox_displacement_move_displacement_movement_mode.addItem("")
        self.comboBox_displacement_move_displacement_movement_mode.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_movement_mode, 8, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self._2.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self._2.addWidget(self.label_4, 0, 1, 1, 1)
        self.comboBox_displacement_move_displacement_velocity = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_velocity.setEnabled(False)
        self.comboBox_displacement_move_displacement_velocity.setObjectName("comboBox_displacement_move_displacement_velocity")
        self.comboBox_displacement_move_displacement_velocity.addItem("")
        self.comboBox_displacement_move_displacement_velocity.addItem("")
        self.comboBox_displacement_move_displacement_velocity.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_velocity, 10, 1, 1, 1)
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.setObjectName("comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis")
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.addItem("")
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.addItem("")
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self._2.addWidget(self.label_7, 7, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self._2.addWidget(self.label_10, 9, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self._2.addWidget(self.label_9, 5, 1, 1, 1)
        self.comboBox_displacement_move_displacement_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_type.setObjectName("comboBox_displacement_move_displacement_type")
        self.comboBox_displacement_move_displacement_type.addItem("")
        self.comboBox_displacement_move_displacement_type.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_type, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self._2.addWidget(self.label_11, 11, 1, 1, 1)
        self.comboBox_displacement_move_displacement_units = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_displacement_move_displacement_units.setEnabled(False)
        self.comboBox_displacement_move_displacement_units.setObjectName("comboBox_displacement_move_displacement_units")
        self.comboBox_displacement_move_displacement_units.addItem("")
        self.comboBox_displacement_move_displacement_units.addItem("")
        self.comboBox_displacement_move_displacement_units.addItem("")
        self._2.addWidget(self.comboBox_displacement_move_displacement_units, 12, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(290, 10, 551, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 171, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 30, 171, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_displacement_move_input_displacement = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_displacement_move_input_displacement.setObjectName("lineEdit_displacement_move_input_displacement")
        self.verticalLayout_2.addWidget(self.lineEdit_displacement_move_input_displacement)
        self.lineEdit_displacement_move_current_displacement = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_displacement_move_current_displacement.setEnabled(False)
        self.lineEdit_displacement_move_current_displacement.setObjectName("lineEdit_displacement_move_current_displacement")
        self.verticalLayout_2.addWidget(self.lineEdit_displacement_move_current_displacement)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(300, 240, 551, 221))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btn_displacement_move_start_move = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_start_move.setGeometry(QtCore.QRect(40, 30, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_displacement_move_start_move.setFont(font)
        self.btn_displacement_move_start_move.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.btn_displacement_move_start_move.setObjectName("btn_displacement_move_start_move")
        self.btn_displacement_move_stop_move = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_stop_move.setGeometry(QtCore.QRect(210, 30, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_displacement_move_stop_move.setFont(font)
        self.btn_displacement_move_stop_move.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.btn_displacement_move_stop_move.setObjectName("btn_displacement_move_stop_move")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 30, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.btn_displacement_move_initiallize_motor = QtWidgets.QPushButton(self.frame_3)
        self.btn_displacement_move_initiallize_motor.setGeometry(QtCore.QRect(40, 120, 101, 71))
        self.btn_displacement_move_initiallize_motor.setObjectName("btn_displacement_move_initiallize_motor")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 120, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(390, 120, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 60, 101, 71))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 60, 101, 71))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(400, 60, 101, 71))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(670, 60, 101, 70))
        self.pushButton_11.setStyleSheet("background-color: rgb(0, 85, 0);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(670, 180, 101, 71))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(670, 300, 101, 71))
        self.pushButton_13.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView.setGeometry(QtCore.QRect(50, 160, 451, 141))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(400, 320, 101, 71))
        self.pushButton_14.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_7.setGeometry(QtCore.QRect(60, 350, 72, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(60, 330, 59, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(211, 329, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 390, 160, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_2)
        self.lcdNumber.setStyleSheet("alternate-background-color: rgb(85, 255, 127);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_3.addWidget(self.lcdNumber)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 420, 160, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.horizontalLayoutWidget_3)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout_4.addWidget(self.lcdNumber_2)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(360, 350, 10, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(212, 353, 142, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(290, 70, 191, 281))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_17.setMaximumSize(QtCore.QSize(179, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.comboBox_CTscan_scan_mode = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboBox_CTscan_scan_mode.setFont(font)
        self.comboBox_CTscan_scan_mode.setObjectName("comboBox_CTscan_scan_mode")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.comboBox_CTscan_scan_mode.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_CTscan_scan_mode)
        self.btn_CTscan_start_scan = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_CTscan_start_scan.setFont(font)
        self.btn_CTscan_start_scan.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.btn_CTscan_start_scan.setObjectName("btn_CTscan_start_scan")
        self.verticalLayout_3.addWidget(self.btn_CTscan_start_scan)
        self.btn_CTscan_stop_scan = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_CTscan_stop_scan.setFont(font)
        self.btn_CTscan_stop_scan.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btn_CTscan_stop_scan.setObjectName("btn_CTscan_stop_scan")
        self.verticalLayout_3.addWidget(self.btn_CTscan_stop_scan)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textEdit = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit.setGeometry(QtCore.QRect(60, 90, 401, 291))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(630, 90, 211, 201))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_17.setGeometry(QtCore.QRect(630, 320, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(180, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_5)
        self.label_19.setGeometry(QtCore.QRect(690, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.btn_quit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_quit.setGeometry(QtCore.QRect(790, 540, 121, 21))
        self.btn_quit.setObjectName("btn_quit")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 943, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CT操作平台"))
        self.label_5.setText(_translate("MainWindow", "请选择参数"))
        self.comboBox_displacement_move_displacement_number.setItemText(0, _translate("MainWindow", "X光机"))
        self.comboBox_displacement_move_displacement_number.setItemText(1, _translate("MainWindow", "G0光栅"))
        self.comboBox_displacement_move_displacement_number.setItemText(2, _translate("MainWindow", "G1光栅"))
        self.comboBox_displacement_move_displacement_number.setItemText(3, _translate("MainWindow", "样品台"))
        self.comboBox_displacement_move_displacement_number.setItemText(4, _translate("MainWindow", "G2光栅"))
        self.label_8.setText(_translate("MainWindow", "位移台类型"))
        self.comboBox_displacement_move_displacement_movement_mode.setItemText(0, _translate("MainWindow", "相对运动"))
        self.comboBox_displacement_move_displacement_movement_mode.setItemText(1, _translate("MainWindow", "绝对运动"))
        self.label_6.setText(_translate("MainWindow", "位移台序号"))
        self.label_4.setText(_translate("MainWindow", "请选择参数"))
        self.comboBox_displacement_move_displacement_velocity.setItemText(0, _translate("MainWindow", "正常"))
        self.comboBox_displacement_move_displacement_velocity.setItemText(1, _translate("MainWindow", "极慢"))
        self.comboBox_displacement_move_displacement_velocity.setItemText(2, _translate("MainWindow", "快一点"))
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_displacement_move_displacement_comboBox_displacement_move_displacement_axis.setItemText(2, _translate("MainWindow", "Z"))
        self.label_7.setText(_translate("MainWindow", "运动模式"))
        self.label_10.setText(_translate("MainWindow", "运动速度"))
        self.label_9.setText(_translate("MainWindow", "轴名称"))
        self.comboBox_displacement_move_displacement_type.setItemText(0, _translate("MainWindow", "平移"))
        self.comboBox_displacement_move_displacement_type.setItemText(1, _translate("MainWindow", "旋转"))
        self.label_11.setText(_translate("MainWindow", "距离单位"))
        self.comboBox_displacement_move_displacement_units.setItemText(0, _translate("MainWindow", "毫米或度"))
        self.comboBox_displacement_move_displacement_units.setItemText(1, _translate("MainWindow", "微米或分"))
        self.comboBox_displacement_move_displacement_units.setItemText(2, _translate("MainWindow", "脉冲"))
        self.label.setText(_translate("MainWindow", "输入运动位移"))
        self.label_2.setText(_translate("MainWindow", "位移台当前位置"))
        self.label_3.setText(_translate("MainWindow", "编码器读数"))
        self.lineEdit_displacement_move_input_displacement.setText(_translate("MainWindow", "0"))
        self.lineEdit_displacement_move_current_displacement.setText(_translate("MainWindow", "0.0000"))
        self.btn_displacement_move_start_move.setText(_translate("MainWindow", "Move"))
        self.btn_displacement_move_stop_move.setText(_translate("MainWindow", "Kill"))
        self.pushButton_3.setText(_translate("MainWindow", "回复负零位"))
        self.btn_displacement_move_initiallize_motor.setText(_translate("MainWindow", "初始化"))
        self.pushButton_5.setText(_translate("MainWindow", "清零"))
        self.pushButton_6.setText(_translate("MainWindow", "回归正零位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "位移运动控制"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "Getting Started"))
        self.pushButton_12.setText(_translate("MainWindow", "Turn On"))
        self.pushButton_13.setText(_translate("MainWindow", "SHUT DOWN"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "1.0mm"))
        self.label_12.setText(_translate("MainWindow", "Focus"))
        self.label_13.setText(_translate("MainWindow", "Exposure Time"))
        self.label_15.setText(_translate("MainWindow", "kV"))
        self.label_16.setText(_translate("MainWindow", "mA"))
        self.label_14.setText(_translate("MainWindow", "S"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "X光机"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "传感器调试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "图像采集"))
        self.label_17.setText(_translate("MainWindow", "扫描方式"))
        self.comboBox_CTscan_scan_mode.setItemText(0, _translate("MainWindow", "相位步进"))
        self.comboBox_CTscan_scan_mode.setItemText(1, _translate("MainWindow", "反转投影"))
        self.comboBox_CTscan_scan_mode.setItemText(2, _translate("MainWindow", "泽尼特"))
        self.btn_CTscan_start_scan.setText(_translate("MainWindow", "开始扫描"))
        self.btn_CTscan_stop_scan.setText(_translate("MainWindow", "急停"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "CT扫描"))
        self.pushButton_17.setText(_translate("MainWindow", "写入日志"))
        self.label_18.setText(_translate("MainWindow", "当天操作历史"))
        self.label_19.setText(_translate("MainWindow", "手动记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "操作日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "装置维护"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "实验室介绍"))
        self.btn_quit.setText(_translate("MainWindow", "退出系统"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))

